- name: Install commonly needed packages for CentOS
  yum:
    name:
      - nfs-utils
      - python3-libselinux
  when: ansible_distribution == 'CentOS'

- name: Install commonly needed packages for Ubuntu
  apt:
    name:
      - nfs-common
      - apt-transport-https
  when: ansible_distribution == 'Ubuntu'

- name: Disable firewalld on CentOS
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_distribution == 'CentOS'
