
- include_tasks: centos-docker-ce.yml
  when: ansible_distribution == 'CentOS'

- name: Set docker version for older k8s
  set_fact:
    docker_version: 18.06
  when: k8s_version.startswith("1.12")

- name: Install docker.io
  apt:
    name: docker.io={{ docker_version }}*
    state: present
  when: ansible_distribution == 'Ubuntu'
