
- include_tasks: centos-docker-ce.yml
  when: ansible_distribution == 'CentOS'

- name: Install docker prereqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add signing key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install docker
  apt:
    name: docker-ce=5:{{ docker_version }}*
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Write docker daemon config file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  when: ansible_distribution == 'Ubuntu'

- name: Create docker service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: Restart docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: ansible_distribution == 'Ubuntu'
