- name: Add hostname to /etc/hosts
  lineinfile:
    destfile: /etc/hosts
    state: present
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"

- name: Make sure `hostname -i` shows the correct IP
  lineinfile:
    destfile: /etc/hosts
    state: absent
    regexp: '^127\.0\.\d+\.\d+\s+{{ inventory_hostname }}'

- name: Remove swap
  lineinfile:
    dest: /etc/fstab
    regexp: '^(.*)swap'
    state: absent
  register: removed_swap

- name: Disable swap
  command: swapoff --all
  when: removed_swap is changed

- include_tasks: centos-kubernetes.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: ubuntu-kubernetes.yml
  when: ansible_distribution == 'Ubuntu'

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes

- name: Check bridged traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables
  register: iptables
  changed_when: False

- name: Pass bridged IPv4 traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables=1
  when: iptables.stdout != "net.bridge.bridge-nf-call-iptables = 1"
