- name: Add hostname to /etc/hosts
  lineinfile:
    destfile: /etc/hosts
    state: present
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"

- name: Make sure `hostname -i` shows the correct IP
  lineinfile:
    destfile: /etc/hosts
    state: absent
    regexp: '^127\.0\.\d+\.\d+\s+{{ inventory_hostname }}'

- name: Remove swap
  lineinfile:
    dest: /etc/fstab
    regexp: '^(.*)swap'
    state: absent
  register: removed_swap

- name: Disable swap
  command: swapoff --all
  when: removed_swap is changed

- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution == 'CentOS'

- name: Install kubernetes parts
  yum:
    name:
      - kubelet-{{ k8s_version }}-0
      - kubeadm-{{ k8s_version }}-0
      - kubectl-{{ k8s_version }}-0
    state: present
    # When ubuntu has ansible version 2.7, enable this again
    # disable_excludes: all
    update_cache: yes
  when: ansible_distribution == 'CentOS'

- name: Install kubernetes parts
  apt:
    name:
      - kubelet={{ k8s_version }}-00
      - kubeadm={{ k8s_version }}-00
      - kubectl={{ k8s_version }}-00
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes

- name: Check bridged traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables
  register: iptables
  changed_when: False

- name: Pass bridged IPv4 traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables=1
  when: iptables.stdout != "net.bridge.bridge-nf-call-iptables = 1"
