- name: Add hostname to /etc/hosts
  lineinfile:
    destfile: /etc/hosts
    state: present
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"

- name: Make sure `hostname -i` shows the correct IP
  lineinfile:
    destfile: /etc/hosts
    state: absent
    regexp: '^127\.0\.\d+\.\d+\s+{{ inventory_hostname }}'

- name: Install commonly needed packages
  yum:
    name:
      - nfs-utils
      - libselinux-python

- name: Remove swap
  lineinfile:
    dest: /etc/fstab
    regexp: '^(.*)swap'
    state: absent
  register: removed_swap

- name: Disable swap
  command: swapoff --all
  when: removed_swap is changed

- include_tasks: docker.yml

- name: Add kubernetes repository
  # Default ansible version on ubuntu does not support "disable_excludes"
  # so we avoid excluding kubernetes packages here.
  # Add this to the block when it is supported.
  # exclude=kube*
  blockinfile:
    create: yes
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive


- name: Install kubernetes parts
  yum:
    name:
      - kubelet-{{ k8s_version }}-0
      - kubeadm-{{ k8s_version }}-0
      - kubectl-{{ k8s_version }}-0
    state: present
    # When ubuntu has ansible version 2.7, enable this again
    # disable_excludes: all
    update_cache: yes

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes

- name: Check bridged traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables
  register: iptables
  changed_when: False

- name: Pass bridged IPv4 traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables=1
  when: iptables.stdout != "net.bridge.bridge-nf-call-iptables = 1"
