---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install python if needed
      become: yes
      become_user: root
      raw: test -e /usr/bin/python || yum install -y python2 || (apt -y update && apt install -y python-minimal)
  tags:
    - prereq

- hosts: nodes
  become: yes
  become_user: root
  strategy: free
  roles:
    - kubernetes-node
  tags:
    - node

- import_playbook: initialize-master.yml
- import_playbook: join-cluster.yml
