---
- hosts: nodes
  become: yes
  become_user: root
  strategy: free
  roles:
    - kubernetes-node
  tags:
    - node

- import_playbook: initialize-master.yml
- import_playbook: ha-control-plane.yml
  when: groups.masters | count > 1
- import_playbook: join-cluster.yml
