---
- hosts: control_plane[0]
  become: yes
  become_user: root
  tasks:

    - name: Get join string
      command: kubeadm token create --print-join-command
      register: string_result

    - name: Store join string
      set_fact:
        join_command: "{{ string_result.stdout }}"

    - name: Upload certificates
      command: kubeadm init phase upload-certs --config=/etc/kubeadm/kubeadm-config.yaml --upload-certs
      register: cert_upload

    - name: Store certificate key
      set_fact:
        cert_key: "{{ cert_upload.stdout_lines | last }}"

- hosts: control_plane[1:]
  become: yes
  become_user: root
  serial: 1
  tasks:
    - name: Join the control plane
      command: "{{ hostvars[groups.control_plane.0].join_command }} --control-plane --certificate-key {{ hostvars[groups.control_plane.0].cert_key }} --apiserver-advertise-address {{ ansible_host }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
