---
- hosts: masters[0]
  become: yes
  become_user: root
  tasks:

    - name: Get join string
      command: kubeadm token create --print-join-command
      register: string_result

    - name: Store join string
      set_fact:
        join_command: "{{ string_result.stdout }}"

    - name: Upload certificates
      command: kubeadm init phase upload-certs --config=/etc/kubeadm/kubeadm-config.yaml --upload-certs
      register: cert_upload
      when: k8s_version.startswith("1.15")

    - name: Store certificate key
      set_fact:
        cert_key: "{{ cert_upload.stdout_lines | last }}"
      when: k8s_version.startswith("1.15")

- import_playbook: copy-master-certificates.yml
  when: not k8s_version.startswith("1.15")

- hosts: masters[1:]
  become: yes
  become_user: root
  serial: 1
  tasks:
    - name: Join the control plane
      command: "{{ hostvars[groups.masters.0].join_command }} --control-plane --certificate-key {{ hostvars[groups.masters.0].cert_key }} --apiserver-advertise-address {{ ansible_host }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: k8s_version.startswith("1.15")

    - name: Join the control plane
      command: "{{ hostvars[groups.masters.0].join_command }} --experimental-control-plane --apiserver-advertise-address {{ ansible_host }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: k8s_version.startswith("1.13") or k8s_version.startswith("1.14")

- import_playbook: ha-1.12.yml
  when: k8s_version.startswith("1.12")
