---
- hosts: clients[0]
  tasks:

    - name: Add helm repos
      command: helm repo add {{ item }}
      loop:
        - metallb https://metallb.github.io/metallb
        - nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
        - ingress-nginx https://kubernetes.github.io/ingress-nginx
        - bitnami https://charts.bitnami.com/bitnami

    - name: Write metallb values file
      template:
        src: metallb-values.yaml.j2
        dest: /home/{{ ansible_user }}/metallb-values.yaml
      tags:
        - metallb

    - name: Deploy metallb
      command: >
        helm upgrade --install metallb metallb/metallb --version 0.12.1
          -f /home/{{ ansible_user }}/metallb-values.yaml
      tags:
        - metallb

    - name: Deploy nfs client provisioner
      command: >
        helm upgrade --install nfs-provisioner --version 4.0.16
          --set nfs.server={{ nfs_server }}
          --set nfs.path={{ nfs_path }}
          --set storageClass.defaultClass=true
          nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
      tags:
        - nfs

    - set_fact:
        worker_ips: "{{ groups.workers | map('extract', hostvars, 'ansible_host') | list }}"
      tags:
        - ingress

    - name: Write values for ingress controller
      blockinfile:
        create: yes
        path: /home/{{ ansible_user }}/ingress-chart-values.yaml
        block: |
          controller:
            # Allow eviction of pod
            # minAvailable: 0  # default: 1
            replicaCount: 2    # default: 1

            service:
              externalIPs: {{ worker_ips | to_yaml }}

            ingressClassResource:
              default: true

          defaultBackend:
            # Allow eviction of pod
            # minAvailable: 0  # default: 1
            replicaCount: 2    # default: 1
      tags:
        - ingress

    - name: Deploy nginx ingress controller
      command: >
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
          --version 4.1.0
          -f /home/{{ ansible_user }}/ingress-chart-values.yaml
      tags:
        - ingress

    - name: Write wordpress values file
      template:
        src: wordpress-values.yaml.j2
        dest: /home/{{ ansible_user }}/wordpress-values.yaml
      tags:
        - wordpress

    - name: Deploy wordpress
      command: >
        helm upgrade --install wordpress bitnami/wordpress
          --version 14.0.4
          -f /home/{{ ansible_user }}/wordpress-production.yaml
      tags:
        - wordpress
