---
- hosts: clients[0]
  tasks:

    - name: Write metallb values file
      template:
        src: metallb-values.yaml.j2
        dest: /home/{{ ansible_user }}/metallb-values.yaml
      tags:
        - metallb

    - name: Deploy metallb
      command: >
        helm upgrade --install metallb stable/metallb --version 0.9.7
          -f /home/{{ ansible_user }}/metallb-values.yaml
      tags:
        - metallb

    - name: Deploy nfs client provisioner
      command: >
        helm upgrade --install nfs-provisioner --version 1.2.6
          --set nfs.server={{ nfs_server }}
          --set nfs.path={{ nfs_path }}
          --set storageClass.defaultClass=true
          stable/nfs-client-provisioner
      tags:
        - nfs

    - set_fact:
        worker_ips: "{{ groups.workers | map('extract', hostvars, 'ansible_host') | list }}"
      tags:
        - ingress

    - name: Write values for ingress controller
      blockinfile:
        create: yes
        path: /home/{{ ansible_user }}/ingress-chart-values.yaml
        block: |
          controller:
            # Allow eviction of pod
            # minAvailable: 0  # default: 1
            replicaCount: 2    # default: 1

            service:
              externalIPs: {{ worker_ips | to_yaml }}

          defaultBackend:
            # Allow eviction of pod
            # minAvailable: 0  # default: 1
            replicaCount: 2    # default: 1
      tags:
        - ingress

    - name: Deploy nginx ingress controller
      command: >
        helm upgrade --install ingress-controller stable/nginx-ingress
          --version 1.6.18
          -f /home/{{ ansible_user }}/ingress-chart-values.yaml
      tags:
        - ingress

    - name: Write wordpress values file
      template:
        src: wordpress-production.yaml.j2
        dest: /home/{{ ansible_user }}/wordpress-production.yaml
      tags:
        - wordpress

    - name: Deploy wordpress
      command: >
        helm upgrade --install wordpress stable/wordpress
          --version 5.12.4
          -f /home/{{ ansible_user }}/wordpress-production.yaml
      tags:
        - wordpress
