---
- hosts: master
  tasks:

    - name: Download helm
      become: yes
      become_user: root
      unarchive:
        src: https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version | default("2.11.0") }}-linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes
      register: download_helm

    - name: Install helm
      become: yes
      become_user: root
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
      when: download_helm is changed

    - name: Init helm
      command: helm init
      tags:
        - helm

    - name: Wait for tiller to start
      command: kubectl get deployment --all-namespaces -l app=helm,name=tiller -o json
      register: tiller_pod
      until: tiller_pod.stdout | from_json | json_query('items[0].status.availableReplicas') >= 1
      retries: 20
      tags:
        - helm

    - name: Deploy nfs client provisioner
      command: >
        helm upgrade --install nfs-provisioner
          --set nfs.server={{ nfs_server }}
          --set nfs.path={{ nfs_path }}
          --set storageClass.defaultClass=true
          stable/nfs-client-provisioner
      tags:
        - nfs

    - set_fact:
        worker_ips: "{{ groups.workers | map('extract', hostvars, 'ansible_host') | list }}"
      tags:
        - ingress

    - name: Write values for ingress controller
      blockinfile:
        create: yes
        path: /home/{{ ansible_user }}/ingress-chart-values.yaml
        block: |
          controller:
            # Allow eviction of pod
            # minAvailable: 0  # default: 1
            replicaCount: 2    # default: 1

            service:
              externalIPs: {{ worker_ips | to_yaml }}

          defaultBackend:
            # Allow eviction of pod
            # minAvailable: 0  # default: 1
            replicaCount: 2    # default: 1
      tags:
        - ingress

    - name: Deploy nginx ingress controller
      command: >
        helm upgrade --install ingress-controller stable/nginx-ingress
          -f /home/{{ ansible_user }}/ingress-chart-values.yaml
      tags:
        - ingress

    - name: Write wordpress values file
      template:
        src: wordpress-production.yaml.j2
        dest: /home/{{ ansible_user }}/wordpress-production.yaml
      tags:
        - wordpress

    - name: Deploy wordpress
      command: >
        helm upgrade --install wordpress stable/wordpress
          -f /home/{{ ansible_user }}/wordpress-production.yaml
      tags:
        - wordpress
