---
- hosts: control_plane[0]
  become: yes
  become_user: root
  tasks:

    - name: Create config directory for kubeadm
      file:
        path: /etc/kubeadm
        state: directory

    - name: Render kubeadm config
      template:
        src: kubeadm-config.yaml.j2
        dest: /etc/kubeadm/kubeadm-config.yaml

    - name: Initialize master
      command: kubeadm init --config=/etc/kubeadm/kubeadm-config.yaml
      args:
        creates: /etc/kubernetes/admin.conf
      register: initialized

    - include_tasks: network-add-on.yml
      when: initialized is changed

    - name: Wait for master to become ready
      command: kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}'
      register: master_node_status
      until: master_node_status.stdout == "True"
      retries: 30
