---
- hosts: masters[0]
  become: yes
  become_user: root
  tasks:

    - name: Create config directory for kubeadm
      file:
        path: /etc/kubeadm
        state: directory

    - name: Render kubeadm config
      template:
        src: kubeadm-config.yaml.j2
        dest: /etc/kubeadm/kubeadm-config.yaml

    - name: Initialize master
      command: kubeadm init --config=/etc/kubeadm/kubeadm-config.yaml
      args:
        creates: /etc/kubernetes/admin.conf
      register: initialized

    - name: Create config directory
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy config
      command: cp /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
      when: initialized is changed

    - name: Set permissions for kubeconfig
      file:
        path: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "u=rw,g=r,o=r"
        state: file

    - name: Store bash completion code for kubectl
      become: yes
      become_user: "{{ ansible_user }}"
      shell: kubectl completion bash > ~/.kube/completion.bash.inc
      args:
        creates: /home/{{ ansible_user }}/.kube/completion.bash.inc

    - name: Enable bash completion for kubectl
      become: yes
      become_user: "{{ ansible_user }}"
      blockinfile:
        path: /home/{{ ansible_user }}/.bashrc
        block: |
          # Kubectl shell completion
          source '/home/{{ ansible_user }}/.kube/completion.bash.inc'

    - name: Install weave network
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
      become: yes
      become_user: "{{ ansible_user }}"
      when: initialized is changed

    # allow all service accounts to act as administrators of the cluster
    # See: https://kubernetes.io/docs/admin/authorization/rbac/
    - name: Set service account permissions
      command: >
        kubectl create clusterrolebinding permissive-binding
          --clusterrole=cluster-admin
          --user=admin
          --user=kubelet
          --group=system:serviceaccounts
      become: yes
      become_user: "{{ ansible_user }}"
      when: initialized is changed

    # Add more masters

    - name: Get join string
      command: kubeadm token create --print-join-command
      register: string_result

    - name: Store join string
      set_fact:
        join_command: "{{ string_result.stdout }}"

    - name: Copy certificates from first master
      fetch:
        src: /etc/kubernetes/{{ item }}
        dest: tmp/{{ item }}
        flat: yes
      with_items:
        - pki/ca.crt
        - pki/ca.key
        - pki/sa.key
        - pki/sa.pub
        - pki/front-proxy-ca.crt
        - pki/front-proxy-ca.key
        - pki/etcd/ca.crt
        - pki/etcd/ca.key
        - admin.conf

- hosts: masters[1:]
  become: yes
  become_user: root
  tasks:
    - name: Create directories
      file:
        path: /etc/kubernetes/{{ item }}
        state: directory
      with_items:
        - pki
        - pki/etcd

    - name: Copy certificates to other masters
      copy:
        src: tmp/{{ item }}
        dest: /etc/kubernetes/{{ item }}
        owner: root
        group: root
      with_items:
        - pki/ca.crt
        - pki/ca.key
        - pki/sa.key
        - pki/sa.pub
        - pki/front-proxy-ca.crt
        - pki/front-proxy-ca.key
        - pki/etcd/ca.crt
        - pki/etcd/ca.key
        - admin.conf

    - name: Correct permissions
      file:
        path: /etc/kubernetes/{{ item }}
        mode: u=rw,g=,o=
      with_items:
        - pki/ca.key
        - pki/sa.key
        - pki/sa.pub
        - pki/front-proxy-ca.key
        - pki/etcd/ca.key
        - admin.conf

    - name: Join the control plane
      command: "{{ hostvars[groups.masters.0].join_command }} --experimental-control-plane"
      args:
        creates: /etc/kubernetes/kubelet.conf
