---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install python if needed
      become: yes
      become_user: root
      raw: test -e {{ ansible_python_interpreter }} || dnf install -y python36 || (apt -y update && apt install -y python3-minimal)
  tags:
    - prereq

- import_playbook: wireguard.yml
  when: wireguard.enabled
  tags:
    - vpn

- hosts: loadbalancers
  become: yes
  become_user: root
  strategy: free
  roles:
    - loadbalancer
  tags:
    - loadbalancer

- hosts: nfs_servers
  become: yes
  become_user: root
  strategy: free
  roles:
    - nfs-server
  tags:
    - nfs

- import_playbook: deploy-kubernetes.yml
  tags:
    - kubernetes

- import_playbook: set-up-client.yml
  tags:
    - client

- import_playbook: helm-charts.yml
  tags:
    - charts
