---
- hosts: loadbalancers
  become: yes
  become_user: root
  strategy: free
  roles:
    - loadbalancer
  tags:
    - loadbalancer

- hosts: nfs_servers
  become: yes
  become_user: root
  strategy: free
  roles:
    - nfs-server
  tags:
    - nfs

- import_playbook: deploy-kubernetes.yml

- import_playbook: helm-charts.yml
  tags:
    - charts
