---
- import_playbook: deploy-kubernetes.yml

- hosts: nfs_servers
  become: yes
  become_user: root
  roles:
    - nfs-server
    - loadbalancer
  tags:
    - nfs
    - loadbalancer

- import_playbook: helm-charts.yml
  tags:
    - charts
