- name: Install haproxy
  package:
    name: haproxy
    state: present

- name: Install commonly needed packages
  yum:
    name: python3-libselinux
  when: ansible_distribution == 'CentOS'

- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution == 'CentOS'

- name: Render haproxy configuration
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      listen stats
          bind *:9000
          mode http
          stats enable
          stats uri /stats
          stats auth admin:admin
      {% if 'control_plane' in groups %}
      frontend control_plane
          bind *:6443
          mode tcp
          default_backend k8s_control_plane
      backend k8s_control_plane
          balance roundrobin
          mode tcp
          {% for node in groups.control_plane -%}
          server {{ node }} {{ hostvars[node].ansible_host }}:6443 check
          {% endfor %}
      {% endif %}

- name: Start haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes
